name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiY2ZlMmM4ZDgtNzhkMC00NjRiLTlmNzAtZGI1ZmEyYzBmNjE5IiwidGVuYW50X2lkIjoiMDcyNTZjNTY2OGI0Njk4OTFkODEzZjk5ZmJhN2YwMGNiYzJkYWYzMWY2NmY5ZWRmZTAxMGY1MzQ3ZTk2YjJlZCIsImludGVybmFsX3NlY3JldCI6IjNhNTNmNWQ5LTZmNjYtNDczZi1hYzQ0LWUxMDhmZmNlNWI5NCJ9.kQxo3H6kr_7qruwH2-8P6pn_0N4kIuRY1rFTCbjp70s"
JWT_SECRET = "topSecret"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"